### ISSUE TITLE
The Authorization Request is not working anymore

### ISSUE THREAD

**Issue by RandomModderJDK** [aimok04/iserv_exercise_discord_webhook#4]
The $host:$port/iserv/login_check url doesn't respond with a valid cookie, it just says that the credentials are invalid. I tried to find a solution(as so often), and I think the best solution is to replace it with /iserv/auth/login as it does basically the same.

**Comment by aimok04** [comment]
Hi!

Is replacing the auth url working for you? Because it does not work on my school's server. 

Recently the in-browser login process was changed and is now way more complicated than it used to be (at least on my school's server). 
The user snickersbrot mentioned me and some other guys in a issue of a repo of them asking for help
(https://github.com/Snickersbrot/IServ-login/issues/1) and I've found a solution but forgot to update my repo.

I'll definitely do that tomorrow.
Thx again for letting me know!

**Comment by RandomModderJDK** [comment]
Oh damn, well it gets a Cookie, so ist doesnt give a error message, but it also doesnt load more than that.

**Comment by RandomModderJDK** [comment]
I just noticed that issue when I was putting it onto my pi, so i thought its just the pi which is busy with loading. So it doesn't work for me neither apparently.

**Comment by aimok04** [comment]
> Oh damn, well it gets a Cookie, so ist doesnt give a error message, but it also doesnt load more than that.

Yeah that's just a temporary cookie which is needed to get the actual session cookie

**Comment by aimok04** [comment]
Decided to do it today! I added the node-fetch lib so you'll have to use `npm i` again when you update. Pls let me know if this also works for you!

**Comment by RandomModderJDK** [comment]
It works absolutely fine, nice job. 🙂
